name: crypto-square

dependencies:
  - base

library:
  exposed-modules: CryptoSquare
  source-dirs: src
  dependencies:
      - split
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - crypto-square
      - hspec
